# Generated by Django 4.0.2 on 2022-02-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_user_is_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(default='', max_length=255),
        ),
    ]
