# Generated by Django 4.0.2 on 2022-02-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='email_type',
            field=models.CharField(default='mail', max_length=255),
        ),
        migrations.AddField(
            model_name='mail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
